### ISSUE TITLE
Inherit point doesn't show properly

### ISSUE THREAD

**Issue by KenZync** [kionell/osu-parsers#25]
![image](https://github.com/kionell/osu-parsers/assets/18224778/ac006547-718f-474c-82e5-810c71e0ade8)
![image](https://github.com/kionell/osu-parsers/assets/18224778/cffb82a8-9a9f-457a-8431-07743acde1aa)

so I have 6 sv but it show just 3 because it is same multiplier?
but it should show all because i want to know startTime for each SV

https://osu.ppy.sh/beatmapsets/618710#mania/1321833

![image](https://github.com/kionell/osu-parsers/assets/18224778/e4afb4e6-18c8-469f-b22e-10988098f291)

![image](https://github.com/kionell/osu-parsers/assets/18224778/a3193605-42ee-42d3-8158-19b401549d57)

![image](https://github.com/kionell/osu-parsers/assets/18224778/32751ec2-fe2d-411d-897c-9c08aa61b4c6)

**Comment by KenZync** [comment]
![image](https://github.com/kionell/osu-parsers/assets/18224778/32751ec2-fe2d-411d-897c-9c08aa61b4c6)

**Comment by KenZync** [comment]
timingPoint ok but difficultyPoint are not

**Comment by kionell** [comment]
> so I have 6 sv but it show just 3 because it is same multiplier?

Correct! I don't know exactly how osu!stable handles timing points, but It's 100% different from osu!lazer.
Although I'm not sure what difficulty you meant, since none of them have the same timing points as in the screenshots above, so let's assume it's `[4K] CHALLENGE! (Marathon)`.

![image](https://github.com/kionell/osu-parsers/assets/43014304/22a54c0f-3f65-42c7-92ac-e30b46c8d83f) ![image](https://github.com/kionell/osu-parsers/assets/43014304/2f3c8381-e684-4344-8d8e-9026694a1cf1)

As you can see, in osu!stable for each timing point there are corresponding difficulty and effect points.

![image](https://github.com/kionell/osu-parsers/assets/43014304/002c1937-a17e-409d-87ec-0492b0da8615)
![image](https://github.com/kionell/osu-parsers/assets/43014304/ec6d7700-3d63-4940-827b-87742cc3737a)

Meanwhile in osu!lazer default (1.0x) & duplicated points are completely ignored, because only those 3 points make any difference to the gameplay. You can read more about that in the [source code](https://github.com/ppy/osu/blob/master/osu.Game/Beatmaps/ControlPoints/ControlPointInfo.cs#L256-L273).

> but it should show all because i want to know startTime for each SV

If I understand correctly, in osu!stable all SV's appear on each timing point. The only possible solution I see is to populate difficulty points manually by using `controlPoints.difficultyPointAt()` for each time when you reach a new timing point.

**Comment by KenZync** [comment]
That would cause troublesome for me. I am calculating BPM * SV = new BPM which for loop from all points and calculate from TimingPoint.bpm * DifficultyPoint.sliderVelocity. but some sv are ignored so it will not correct. What do you think?

**Comment by kionell** [comment]
I think in that case you can do:
```js
const bpm = beatmap.controlPoints.groups.map((group) => {
  const timingPoint = beatmap.controlPoints.timingPointAt(group.startTime);
  const difficultyPoint = beatmap.controlPoints.difficultyPointAt(group.startTime);

  return timingPoint.bpm * difficultyPoint.slidetVelocity;
});
```

This will allow you to find the BPM at each moment in time when new control points appear. As an alternative you can iterate over timing points instead of groups

**Comment by KenZync** [comment]
> I think in that case you can do:
> 
> ```js
> const bpm = beatmap.controlPoints.groups.map((group) => {
>   const timingPoint = beatmap.controlPoints.timingPointAt(group.startTime);
>   const difficultyPoint = beatmap.controlPoints.difficultyPointAt(group.startTime);
> 
>   return timingPoint.bpm * difficultyPoint.slidetVelocity;
> });
> ```
> 
> This will allow you to find the BPM at each moment in time when new control points appear. As an alternative you can iterate over timing points instead of groups

oh that would solve issue Thank you!
Btw I'm doing Osu to O2Jam converter and it's doing great!
