### ISSUE TITLE
beatLength, bpm calculation is wrong when bpm is > 10000 or bpm <1

### ISSUE THREAD

**Issue by KenZync** [kionell/osu-parsers#26]
![image](https://github.com/kionell/osu-parsers/assets/18224778/718645cf-c519-47d2-885e-d2a77769ec47)

![image](https://github.com/kionell/osu-parsers/assets/18224778/87968343-933d-447a-b5e4-9cbae42f0ec9)

**Comment by KenZync** [comment]
i cant access _beatLength that is correct because it is private

**Comment by kionell** [comment]
As I can see you are refering to osu!stable. Unlike osu!stable, in osu!lazer the beat length values are limited from 6 to 60 000 which means you can't have BPM below 1 or above 10 000. You can verify this yourself by looking at the [game’s source code](https://github.com/ppy/osu/blob/master/osu.Game/Beatmaps/ControlPoints/TimingControlPoint.cs#L65-L78) or simply by opening the map editor in osu!lazer. I don't think I can change that because it can affect star rating calculation, but I can expose raw value as a different property if you really need it.

**Comment by KenZync** [comment]
Expose RawBeatlength Yes Please!

**Comment by kionell** [comment]
> Expose RawBeatlength Yes Please!

New properties already available in the newest update.
You can use beatLengthUnlimited and sliderVelocityUnlimited to get full values. I want to add that osu!mania uses effect points and scroll speed rather than difficulty points and slider velocity. Scroll speed also has it's unlimited variant
