### ISSUE TITLE
ScoreDecoder is not working in Browser environiment

### ISSUE THREAD

**Issue by cunev** [kionell/osu-parsers#8]
There's no Buffer in the browser, hence the reason replays fail to decode.
A workaround is to use the "buffer" module from npm.

Workaround example:
```ts
import { Buffer } from "buffer";
async function getReplay(){
  const requestResponse = await fetch("/replay.osr")
  const arrayBuffer = await requestResponse.arrayBuffer()
  await decoder.decodeFromBuffer(Buffer.from(arrayBuffer));
}
```

It would be way better to have decodeFromBuffer accept ArrayBuffer.

**Comment by kionell** [comment]
> A workaround is to use the "buffer" module from npm.

Yeah, it's already listed in the dependencies of this package.
I did it because initially the project was written to support node.js only and heavy relied on some of the Buffer's methods (such as readUint8, readInt16, etc). I will most likely get rid of that polyfill and implement those methods myself.

**Comment by kionell** [comment]
> It would be way better to have decodeFromBuffer accept ArrayBuffer.

Added in the new v4.0.0 major update.
All decoders now accept `ArrayBufferLike | Uint8Array` which allows to use Uint8Array, Node.js Buffer and Browser ArrayBuffer as input data.
As a result `ScoreEncoder` now outputs `Uint8Array` instead of `Buffer`.
